### ISSUE TITLE
datetime_convery.py syntax error

### ISSUE THREAD

**Issue by jcancell** [aderusso/120class123#10]
Description: Syntax error occurs on last line of code.

Expected Behavior: Statement prints formatted date string

Actual Behavior: Syntax Error

Additional Information

Operating System: Windows 10
Browser: Google Chrome
Version: Chrome Browser v 111.0

Possible Solution: Close statement in parenthesis

Priority: High

Reproducibility: Always

Impact: High

**Comment by aderusso** [comment]
added parenthesis at end of last line
