### ISSUE TITLE
Something doesn't

### ISSUE THREAD

**Issue by aderusso** [aderusso/120class123#13]
sum_even_fibbionacci.cc
Description: missing type specifier

Steps to Reproduce

run program

Expected Behavior: file works and runs

Actual Behavior: error

Additional Information

Operating System: Windows 64
Browser: Tor
Version: 120

Possible Solution: add type specifier

Priority: High

Reproducibility: easy/every time

Impact: High file encounters error

**Comment by aphayes2025** [comment]
Fixed the error for the type specifier.
