### ISSUE TITLE
sum_even_fibo.java compiler bug

### ISSUE THREAD

**Issue by dlaberg2** [aderusso/120class123#7]
Description: The file does not compile when it is run

Steps to Reproduce
   1. When you run the program it does not compile due to errors

Expected Behavior: When you run the program it is supposed to successfully run

Actual Behavior: It does not compile when run

Screenshots If applicable, add screenshots to help explain the issue/bug.

Additional Information

    Operating System: Windows 11
    Browser: Firefox
    Version: Version 1.1(Win 64)
    Any other relevant information

Possible Solution If you have any suggestions for a possible solution, please include them here.
Find an issue with the syntax that would stop the program from compiling

Related Issues Are there any related issues? If so, please link to them here.
N/A

Priority How critical is this issue/bug? Low, medium, or high priority?
High priority, file does not run

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
It always takes place

Impact What is the impact of this issue/bug? Low, medium, or high?
High, File does not run with this issue

**Comment by aphayes2025** [comment]
I fixed the error causing the program not to compile.
